#ifndef _KERNELS_REG_H_
#define _KERNELS_REG_H_

typedef enum
{
    F1_KERNEL_REG,
    F10_KERNEL_REG,
    F11_KERNEL_REG,
    F12_KERNEL_REG,
    F13_KERNEL_REG,
    F14_KERNEL_REG,
    F15_KERNEL_REG,
    F16_KERNEL_REG,
    F17_KERNEL_REG,
    F18_KERNEL_REG,
    F19_KERNEL_REG,
    F2_KERNEL_REG,
    F20_KERNEL_REG,
    F21_KERNEL_REG,
    F22_KERNEL_REG,
    F23_KERNEL_REG,
    F24_KERNEL_REG,
    F3_KERNEL_REG,
    F4_KERNEL_REG,
    F5_KERNEL_REG,
    F6_KERNEL_REG,
    F7_KERNEL_REG,
    F8_KERNEL_REG,
    F9_KERNEL_REG,
    
    FIND_BEST_WORST_ALT_KERNEL_REG,
    FIND_BEST_WORST_ALT2_KERNEL_REG,
    FIND_BEST_WORST_VEC2_KERNEL_REG,

    FIND_MIN_VEC_KERNEL_REG,

    INIT_ROT_MATRIX_VEC_KERNEL_REG,

    PARTICLE_INIT_VEC_KERNEL_REG,

    SWAP_PARTICLES_VEC_KERNEL_REG,

    UPDATE_BEST_VALS_VEC_KERNEL_REG,
    
    UPDATE_POS_VEL_VEC_KERNEL_REG,

    UPDATE_SAMPLES_VEC_KERNEL_REG,
    
    NUM_KERNELS_REG
} kernel_names_reg;

#endif
