#ifndef _KERNELS_MCS_H_
#define _KERNELS_MCS_H_

typedef enum
{
    //these must be arranged in alphabetical order by kernel function name!
    CROSSOVER_VEC_KERNEL_MCS,
    
    F1_KERNEL_MCS,
    F10_KERNEL_MCS,
    F11_KERNEL_MCS,
    F12_KERNEL_MCS,
    F13_KERNEL_MCS,
    F14_KERNEL_MCS,
    F15_KERNEL_MCS,
    F16_KERNEL_MCS,
    F17_KERNEL_MCS,
    F18_KERNEL_MCS,
    F19_KERNEL_MCS,
    F2_KERNEL_MCS,
    F20_KERNEL_MCS,
    F21_KERNEL_MCS,
    F22_KERNEL_MCS,
    F23_KERNEL_MCS,
    F24_KERNEL_MCS,
    F3_KERNEL_MCS,
    F4_KERNEL_MCS,
    F5_KERNEL_MCS,
    F6_KERNEL_MCS,
    F7_KERNEL_MCS,
    F8_KERNEL_MCS,
    F9_KERNEL_MCS,
    
    FIND_BEST_WORST_ALT_KERNEL_MCS,
    FIND_BEST_WORST_ALT2_KERNEL_MCS,
    FIND_BEST_WORST_VEC2_KERNEL_MCS,

    FIND_MIN_VEC_KERNEL_MCS,

    INIT_ROT_MATRIX_VEC_KERNEL_MCS,

    MUT_RESTORE_VEC_KERNEL_MCS,
    
    PARTICLE_INIT_VEC_KERNEL_MCS,

    PERMUTE_VEC_KERNEL_MCS,

    SWAP_PARTICLES_VEC_KERNEL_MCS,

    UPDATE_BEST_VALS_VEC_KERNEL_MCS,
    
    UPDATE_POS_VEL_VEC_KERNEL_MCS,

    UPDATE_SAMPLES_VEC_KERNEL_MCS,
    
    NUM_KERNELS_MCS
} kernel_names_mcs;

#endif
